//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using NHibernate.DomainModel.Northwind.Entities;
using NHibernate.Exceptions;
using NHibernate.Proxy;
using NUnit.Framework;
using NHibernate.Linq;

namespace NHibernate.Test.Linq
{
	using System.Threading.Tasks;
	[TestFixture]
	public class SelectionTestsAsync : LinqTestCase
	{
		[Test]
		public async Task CanGetCountOnQueryWithAnonymousTypeAsync()
		{
			var query = from user in db.Users
						select new { user.Name, RoleName = user.Role.Name };

			int totalCount = await (query.CountAsync());

			Assert.AreEqual(3, totalCount);
		}

		[Test]
		public async Task CanGetFirstWithAnonymousTypeAsync()
		{
			var query = from user in db.Users
						select new { user.Name, RoleName = user.Role.Name };

			var firstUser = await (query.FirstAsync());

			Assert.IsNotNull(firstUser);
		}

		[Test]
		public async Task CanSelectUsingMemberInitExpressionAsync()
		{
			var query = from user in db.Users
						select new UserDto(user.Id, user.Name) { InvalidLoginAttempts = user.InvalidLoginAttempts };

			var list = await (query.ToListAsync());
			Assert.AreEqual(3, list.Count);
		}

		[Test]
		public async Task CanSelectNestedAnonymousTypeAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							Enums = new
							{
								user.Enum1,
								user.Enum2
							},
							RoleName = user.Role.Name
						};

			var list = await (query.ToListAsync());
			Assert.AreEqual(3, list.Count);

			//assert role names -- to ensure that the correct values were used to invoke constructor
			Assert.IsTrue(list.All(u => u.RoleName == "Admin" || u.RoleName == "User" || String.IsNullOrEmpty(u.RoleName)));
		}

		[Test]
		public async Task CanSelectNestedAnonymousTypeWithMultipleReferencesAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							Enums = new
							{
								user.Enum1,
								user.Enum2
							},
							RoleName = user.Role.Name,
							RoleIsActive = (bool?) user.Role.IsActive
						};

			var list = await (query.ToListAsync());
			Assert.AreEqual(3, list.Count);

			//assert role names -- to ensure that the correct values were used to invoke constructor
			Assert.IsTrue(list.All(u => u.RoleName == "Admin" || u.RoleName == "User" || String.IsNullOrEmpty(u.RoleName)));
		}

		[Test]
		public async Task CanSelectNestedAnonymousTypeWithComponentReferenceAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							Enums = new
							{
								user.Enum1,
								user.Enum2
							},
							RoleName = user.Role.Name,
							ComponentProperty = user.Component.Property1
						};

			var list = await (query.ToListAsync());
			Assert.AreEqual(3, list.Count);

			//assert role names -- to ensure that the correct values were used to invoke constructor
			Assert.IsTrue(list.All(u => u.RoleName == "Admin" || u.RoleName == "User" || String.IsNullOrEmpty(u.RoleName)));
		}

		[Test]
		public async Task CanSelectNestedMemberInitExpressionAsync()
		{
			var query = from user in db.Users
						select new UserDto(user.Id, user.Name)
						{
							InvalidLoginAttempts = user.InvalidLoginAttempts,
							Dto2 = new UserDto2
									   {
								RegisteredAt = user.RegisteredAt,
								Enum = user.Enum2
							},
							RoleName = user.Role.Name
						};

			var list = await (query.ToListAsync());
			Assert.AreEqual(3, list.Count);

			//assert role names -- to ensure that the correct values were used to invoke constructor
			Assert.IsTrue(list.All(u => u.RoleName == "Admin" || u.RoleName == "User" || String.IsNullOrEmpty(u.RoleName)));
		}

		[Test]
		public async Task CanSelectNestedMemberInitWithinNewExpressionAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							user.InvalidLoginAttempts,
							Dto = new UserDto2
									  {
								RegisteredAt = user.RegisteredAt,
								Enum = user.Enum2
							},
							RoleName = user.Role.Name
						};

			var list = await (query.ToListAsync());
			Assert.AreEqual(3, list.Count);

			//assert role names -- to ensure that the correct values were used to invoke constructor
			Assert.IsTrue(list.All(u => u.RoleName == "Admin" || u.RoleName == "User" || String.IsNullOrEmpty(u.RoleName)));
		}

		[Test]
		public async Task CanSelectSinglePropertyAsync()
		{
			var query = from user in db.Users
						where user.Name == "ayende"
						select user.RegisteredAt;

			DateTime date = await (query.SingleAsync());
			Assert.AreEqual(new DateTime(2010, 06, 17), date);
		}

		[Test]
		public async Task CanSelectBinaryExpressionsAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							IsSmall = (user.Enum1 == EnumStoredAsString.Small)
						};

			var list = await (query.ToListAsync());

			foreach (var user in list)
			{
				if (user.Name == "rahien")
				{
					Assert.IsTrue(user.IsSmall);
				}
				else
				{
					Assert.IsFalse(user.IsSmall);
				}
			}
		}

		[Test]
		public async Task CanSelectWithMultipleBinaryExpressionsAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							IsAyende = (user.Enum1 == EnumStoredAsString.Medium
								&& user.Enum2 == EnumStoredAsInt32.High)
						};

			var list = await (query.ToListAsync());

			foreach (var user in list)
			{
				if (user.Name == "ayende")
				{
					Assert.IsTrue(user.IsAyende);
				}
				else
				{
					Assert.IsFalse(user.IsAyende);
				}
			}
		}

		[Test]
		public async Task CanSelectWithMultipleBinaryExpressionsWithOrAsync()
		{
			var query = from user in db.Users
						select new
						{
							user.Name,
							IsAyende = (user.Name == "ayende"
								|| user.Name == "rahien")
						};

			var list = await (query.ToListAsync());

			foreach (var user in list)
			{
				if (user.Name == "ayende" || user.Name == "rahien")
				{
					Assert.IsTrue(user.IsAyende);
				}
				else
				{
					Assert.IsFalse(user.IsAyende);
				}
			}
		}

		[Test]
		public async Task CanSelectWithAnySubQueryAsync()
		{
			var query = from timesheet in db.Timesheets
						select new
						{
							timesheet.Id,
							HasEntries = timesheet.Entries.Any()
						};

			var list = await (query.ToListAsync());

			Assert.AreEqual(2, list.Count(t => t.HasEntries));
			Assert.AreEqual(1, list.Count(t => !t.HasEntries));
		}

		[Test]
		public async Task CanSelectConditionalAsync()
		{
			using (var sqlLog = new SqlLogSpy())
			{
				var q = await (db.Orders.Where(o => o.Customer.CustomerId == "test")
						   .Select(o => o.ShippedTo.Contains("test") ? o.ShippedTo : o.Customer.CompanyName)
						   .OrderBy(o => o)
						   .Distinct()
						   .ToListAsync());

				Assert.That(FindAllOccurrences(sqlLog.GetWholeLog(), "case"), Is.EqualTo(2));
			}

			using (var sqlLog = new SqlLogSpy())
			{
				var q = await (db.Orders.Where(o => o.Customer.CustomerId == "test")
						   .Select(o => o.OrderDate.HasValue ? o.OrderDate : o.ShippingDate)
						   .FirstOrDefaultAsync());

				Assert.That(FindAllOccurrences(sqlLog.GetWholeLog(), "case"), Is.EqualTo(1));
			}

			using (var sqlLog = new SqlLogSpy())
			{
				var q = await (db.Orders.Where(o => o.Customer.CustomerId == "test")
						   .Select(o => new
						   {
							   Value = o.OrderDate.HasValue
								   ? o.Customer.CompanyName
								   : (o.ShippingDate.HasValue
									? o.Shipper.CompanyName + "Shipper"
									: o.ShippedTo)
						   })
						   .FirstOrDefaultAsync());

				var log = sqlLog.GetWholeLog();
				Assert.That(FindAllOccurrences(log, "as col"), Is.EqualTo(1));
			}

			using (var sqlLog = new SqlLogSpy())
			{
				var q = await (db.Orders.Where(o => o.Customer.CustomerId == "test")
				          .Select(o => new
				          {
					          Value = o.OrderDate.HasValue
						          ? o.Customer.CompanyName
						          : (o.ShippingDate.HasValue
							          ? o.Shipper.CompanyName + "Shipper"
									  : null)
				          })
				          .FirstOrDefaultAsync());

				var log = sqlLog.GetWholeLog();
				Assert.That(FindAllOccurrences(log, "as col"), Is.EqualTo(1));
			}

			using (var sqlLog = new SqlLogSpy())
			{
				var q = await (db.Orders.Where(o => o.Customer.CustomerId == "test")
						  .Select(o => new
						  {
							  Value = o.OrderDate.HasValue
								  ? o.Customer.CompanyName
								  : (o.ShippingDate.HasValue
									  ? o.Shipper.CompanyName + "Shipper"
									  : "default")
						  })
						  .FirstOrDefaultAsync());

				var log = sqlLog.GetWholeLog();
				Assert.That(FindAllOccurrences(log, "as col"), Is.EqualTo(1));
			}

			var defaultValue = "default";
			using (var sqlLog = new SqlLogSpy())
			{
				var q = await (db.Orders.Where(o => o.Customer.CustomerId == "test")
						  .Select(o => new
						  {
							  Value = o.OrderDate.HasValue
								  ? o.Customer.CompanyName
								  : (o.ShippingDate.HasValue
									  ? o.Shipper.CompanyName + "Shipper"
									  : defaultValue)
						  })
						  .FirstOrDefaultAsync());

				var log = sqlLog.GetWholeLog();
				Assert.That(FindAllOccurrences(log, "as col"), Is.EqualTo(1));
			}
		}

		[Test]
		public async Task CanSelectConditionalSubQueryAsync()
		{
			if (!Dialect.SupportsScalarSubSelects)
				Assert.Ignore(Dialect.GetType().Name + " does not support scalar sub-queries");

			var list = await (db.Customers
						   .Select(c => new
						   {
							   Date = db.Orders.Where(o => o.Customer.CustomerId == c.CustomerId)
										.Select(o => o.OrderDate.HasValue ? o.OrderDate : o.ShippingDate)
										.Max()
						   })
						   .ToListAsync());
			Assert.That(list, Has.Count.GreaterThan(0));

			var list2 = await (db.Orders
			              .Select(
				              o => new
				              {
					              UnitPrice = o.Freight.HasValue
						              ? o.OrderLines.Where(l => l.Discount == 1)
						                 .Select(l => l.Product.UnitPrice.HasValue ? l.Product.UnitPrice : l.UnitPrice)
						                 .Max()
						              : o.OrderLines.Where(l => l.Discount == 0)
						                 .Select(l => l.Product.UnitPrice.HasValue ? l.Product.UnitPrice : l.UnitPrice)
						                 .Max()
				              })
			              .ToListAsync());
			Assert.That(list2, Has.Count.GreaterThan(0));

			var list3 = await (db.Orders
						  .Select(o => new
						  {
							  Date = o.OrderLines.Any(l => o.OrderDate.HasValue)
								  ? db.Employees
									  .Select(e => e.BirthDate.HasValue ? e.BirthDate : e.HireDate)
									  .Max()
								  : o.Employee.Superior != null ? o.Employee.Superior.BirthDate : o.Employee.BirthDate
						  })
						  .ToListAsync());
			Assert.That(list3, Has.Count.GreaterThan(0));
		}

		[Test, KnownBug("NH-3045")]
		public async Task CanSelectFirstElementFromChildCollectionAsync()
		{
			using (var log = new SqlLogSpy())
			{
				var orders = await (db.Customers
					.Select(customer => customer.Orders.OrderByDescending(x => x.OrderDate).First())
					.ToListAsync());

				Assert.That(orders, Has.Count.GreaterThan(0));

				var text = log.GetWholeLog();
				var count = text.Split(new[] { "SELECT" }, StringSplitOptions.None).Length - 1;
				Assert.That(count, Is.EqualTo(1));
			}
		}

		[Test]
		public async Task CanProjectWithCastAsync()
		{
			// NH-2463
			// ReSharper disable RedundantCast

			var names1 = await (db.Users.Select(p => new { p1 = p.Name }).ToListAsync());
			Assert.AreEqual(3, names1.Count);

			var names2 = await (db.Users.Select(p => new { p1 = ((User) p).Name }).ToListAsync());
			Assert.AreEqual(3, names2.Count);

			var names3 = await (db.Users.Select(p => new { p1 = (p as User).Name }).ToListAsync());
			Assert.AreEqual(3, names3.Count);

			var names4 = await (db.Users.Select(p => new { p1 = ((IUser) p).Name }).ToListAsync());
			Assert.AreEqual(3, names4.Count);

			var names5 = await (db.Users.Select(p => new { p1 = (p as IUser).Name }).ToListAsync());
			Assert.AreEqual(3, names5.Count);
			// ReSharper restore RedundantCast
		}

		[Test]
		public async Task CanSelectAfterOrderByAndTakeAsync()
		{
			// NH-3320
			var names = await (db.Users.OrderBy(p => p.Name).Take(3).Select(p => p.Name).ToListAsync());
			Assert.AreEqual(3, names.Count);
		}

		[Test]
		public async Task CanSelectManyWithCastAsync()
		{
			// NH-2688
			// ReSharper disable RedundantCast
			var orders1 = await (db.Customers.Where(c => c.CustomerId == "VINET").SelectMany(o => o.Orders).ToListAsync());
			Assert.AreEqual(5, orders1.Count);

			//$exception	{"c.Orders is not mapped [.SelectMany[NHibernate.DomainModel.Northwind.Entities.Customer,NHibernate.DomainModel.Northwind.Entities.Order](.Where[NHibernate.DomainModel.Northwind.Entities.Customer](NHibernate.Linq.NhQueryable`1[NHibernate.DomainModel.Northwind.Entities.Customer], Quote((c, ) => (String.op_Equality(c.CustomerId, p1))), ), Quote((o, ) => (Convert(o.Orders))), )]"}	System.Exception {NHibernate.Hql.Ast.ANTLR.QuerySyntaxException} 
			// Block OData navigation to detail request requests like 
			// http://localhost:2711/TestWcfDataService.svc/TestEntities(guid&#39;0dd52f6c-1943-4013-a88e-3b63a1fbe11b&#39;)/Details1 
			var orders2 = await (db.Customers.Where(c => c.CustomerId == "VINET").SelectMany(o => (ISet<Order>) o.Orders).ToListAsync());
			Assert.AreEqual(5, orders2.Count);

			//$exception	{"([100001].Orders As ISet`1)"}	System.Exception {System.NotSupportedException} 
			var orders3 = await (db.Customers.Where(c => c.CustomerId == "VINET").SelectMany(o => (o.Orders as ISet<Order>)).ToListAsync());
			Assert.AreEqual(5, orders3.Count);

			var orders4 = await (db.Customers.Where(c => c.CustomerId == "VINET").SelectMany(o => (IEnumerable<Order>) o.Orders).ToListAsync());
			Assert.AreEqual(5, orders4.Count);

			var orders5 = await (db.Customers.Where(c => c.CustomerId == "VINET").SelectMany(o => (o.Orders as IEnumerable<Order>)).ToListAsync());
			Assert.AreEqual(5, orders5.Count);
			// ReSharper restore RedundantCast
		}

		[Test]
		public async Task CanSelectCollectionAsync()
		{
			var orders = await (db.Customers.Where(c => c.CustomerId == "VINET").Select(o => o.Orders).ToListAsync());
			Assert.AreEqual(5, orders[0].Count);
		}

		[Test]
		public async Task CanSelectConditionalKnownTypesAsync()
		{
			if (!Dialect.SupportsScalarSubSelects)
				Assert.Ignore(Dialect.GetType().Name + " does not support scalar sub-queries");

			var moreThanTwoOrderLinesBool = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? true : false, Param = true }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesBool.Count(x => x.HasMoreThanTwo == true), Is.EqualTo(410));

			var moreThanTwoOrderLinesNBool = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? true : (bool?)null, Param = (bool?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNBool.Count(x => x.HasMoreThanTwo == true), Is.EqualTo(410));

			var moreThanTwoOrderLinesShort = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? (short)1 : (short)0, Param = (short)0 }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesShort.Count(x => x.HasMoreThanTwo == 1), Is.EqualTo(410));

			var moreThanTwoOrderLinesNShort = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? (short?)1 : (short?)null, Param = (short?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNShort.Count(x => x.HasMoreThanTwo == 1), Is.EqualTo(410));

			var moreThanTwoOrderLinesInt = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1 : 0, Param = 1 }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesInt.Count(x => x.HasMoreThanTwo == 1), Is.EqualTo(410));

			var moreThanTwoOrderLinesNInt = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1 : (int?)null, Param = (int?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNInt.Count(x => x.HasMoreThanTwo == 1), Is.EqualTo(410));

			var moreThanTwoOrderLinesDecimal = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1m : 0m, Param = 1m }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesDecimal.Count(x => x.HasMoreThanTwo == 1m), Is.EqualTo(410));

			var moreThanTwoOrderLinesNDecimal = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1m : (decimal?)null, Param = (decimal?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNDecimal.Count(x => x.HasMoreThanTwo == 1m), Is.EqualTo(410));

			var moreThanTwoOrderLinesSingle = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1f : 0f, Param = 1f }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesSingle.Count(x => x.HasMoreThanTwo == 1f), Is.EqualTo(410));

			var moreThanTwoOrderLinesNSingle = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1f : (float?)null, Param = (float?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNSingle.Count(x => x.HasMoreThanTwo == 1f), Is.EqualTo(410));

			var moreThanTwoOrderLinesDouble = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1d : 0d, Param = 1d }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesDouble.Count(x => x.HasMoreThanTwo == 1d), Is.EqualTo(410));

			var moreThanTwoOrderLinesNDouble = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? 1d : (double?)null, Param = (double?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNDouble.Count(x => x.HasMoreThanTwo == 1d), Is.EqualTo(410));
			
			var moreThanTwoOrderLinesString = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? "yes" : "no", Param = "no" }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesString.Count(x => x.HasMoreThanTwo == "yes"), Is.EqualTo(410));

			var now = DateTime.Now.Date;
			var moreThanTwoOrderLinesDateTime = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? o.OrderDate.Value : now, Param = now }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesDateTime.Count(x => x.HasMoreThanTwo != now), Is.EqualTo(410));

			var moreThanTwoOrderLinesNDateTime = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? o.OrderDate : null, Param = (DateTime?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNDateTime.Count(x => x.HasMoreThanTwo != null), Is.EqualTo(410));

			var moreThanTwoOrderLinesGuid = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? o.Shipper.Reference : Guid.Empty, Param = Guid.Empty }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesGuid.Count(x => x.HasMoreThanTwo != Guid.Empty), Is.EqualTo(410));

			var moreThanTwoOrderLinesNGuid = await (db.Orders.Select(o => new { Id = o.OrderId, HasMoreThanTwo = o.OrderLines.Count() > 2 ? o.Shipper.Reference : (Guid?)null, Param = (Guid?)null }).ToListAsync());
			Assert.That(moreThanTwoOrderLinesNGuid.Count(x => x.HasMoreThanTwo != null), Is.EqualTo(410));
		}

		[Test]
		public async Task CanSelectConditionalEntityAsync()
		{
			var fatherInsteadOfChild = await (db.Animals.Select(a => a.Father.SerialNumber == "5678" ? a.Father : a).ToListAsync());
			Assert.That(fatherInsteadOfChild, Has.Exactly(2).With.Property("SerialNumber").EqualTo("5678"));
		}

		[Test]
		public async Task CanSelectConditionalEntityWithCastAsync()
		{
			var fatherInsteadOfChild = await (db.Mammals.Select(a => a.Father.SerialNumber == "5678" ? (object)a.Father : (object)a).ToListAsync());
			Assert.That(fatherInsteadOfChild, Has.Exactly(2).With.Property("SerialNumber").EqualTo("5678"));
		}

		[Test]
		public async Task CanSelectConditionalEntityValueAsync()
		{
			var fatherInsteadOfChild = await (db.Animals.Select(a => a.Father.SerialNumber == "5678" ? a.Father.SerialNumber : a.SerialNumber).ToListAsync());
			Assert.That(fatherInsteadOfChild, Has.Exactly(2).EqualTo("5678"));
		}

		[Test]
		public async Task CanSelectConditionalEntityValueWithEntityComparisonAsync()
		{
			var father = await (db.Animals.SingleAsync(a => a.SerialNumber == "5678"));
			var fatherInsteadOfChild = await (db.Animals.Select(a => a.Father == father ? a.Father.SerialNumber : a.SerialNumber).ToListAsync());
			Assert.That(fatherInsteadOfChild, Has.Exactly(2).EqualTo("5678"));
		}

		[Test]
		public async Task CanSelectConditionalEntityValueWithEntityComparisonComplexAsync()
		{
			var animal = await (db.Animals.Select(
				               a => new
				               {
								   Parent = a.Father != null || a.Mother != null ? (a.Father ?? a.Mother) : null,
								   ParentSerialNumber = a.Father != null || a.Mother != null ? (a.Father ?? a.Mother).SerialNumber : null,
								   Parent2 = a.Mother ?? a.Father,
								   a.Father,
								   a.Mother
				               })
			               .FirstOrDefaultAsync(o => o.ParentSerialNumber == "5678"));

			Assert.That(animal, Is.Not.Null);
			Assert.That(animal.Father, Is.Not.Null);
			Assert.That(animal.Mother, Is.Not.Null);
			Assert.That(animal.Parent, Is.Not.Null);
			Assert.That(animal.Parent2, Is.Not.Null);
			Assert.That(NHibernateUtil.IsInitialized(animal.Parent), Is.True);
			Assert.That(NHibernateUtil.IsInitialized(animal.Parent2), Is.True);
			Assert.That(NHibernateUtil.IsInitialized(animal.Father), Is.True);
			Assert.That(NHibernateUtil.IsInitialized(animal.Mother), Is.True);
		}

		[Test]
		public async Task CanSelectConditionalEntityValueWithEntityCastAsync()
		{
			var list = await (db.Animals.Select(
				               a => new
				               {
					               BodyWeight = (double?) (a is Cat 
						               ? (a.Father ?? a.Mother).BodyWeight
										: (a is Dog
											? (a.Mother ?? a.Father).BodyWeight
											: (a.Father.Father.BodyWeight)
						               ))
				               })
			               .ToListAsync());
			Assert.That(list, Has.Exactly(1).With.Property("BodyWeight").Not.Null);
		}

		[Test]
		public void CanSelectWithIsOperatorAsync()
		{
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => a is Dog).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => a.FatherSerialNumber is string).ToListAsync());
		}

		[Test]
		public async Task CanSelectNonMappedComponentPropertyAsync()
		{
			Assert.DoesNotThrowAsync(() => db.Users.Select(u => u.Component.Property3).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Users.Select(u => u.Component.OtherComponent.OtherProperty2).ToListAsync());
			var list = await (db.Users.Select(u => new
			{
				u.Component.OtherComponent.OtherProperty1,
				u.Component.OtherComponent.OtherProperty2,
				u.Component.Property1,
				u.Component.Property2,
				u.Component.Property3
			}).ToListAsync());
			Assert.That(list.Select(o => o.OtherProperty2), Is.EquivalentTo(list.Select(o => o.OtherProperty1)));
			Assert.That(
				list.Select(o => (o.Property1 ?? o.Property2) == null ? null : $"{o.Property1}{o.Property2}"),
				Is.EquivalentTo(list.Select(o => o.Property3)));
		}

		[Test]
		public void CanSelectWithAnInvocationAsync()
		{
			Func<string, string> func = s => s + "postfix";
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => func(a.SerialNumber)).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => func(a.FatherSerialNumber)).ToListAsync());
		}

		[Test]
		public void CanSelectEnumerableAsync()
		{
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new[] { a.Id } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new[] { a.Id, 1 } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new[] { 1 } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new[] { a, a.Father, a.Mother } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new
			{
				Enumerable = new[]
			{
				new UserDto(a.Id, a.FatherSerialNumber) {RoleName = a.FatherSerialNumber},
				new UserDto(1, a.FatherSerialNumber) {RoleName = a.FatherSerialNumber, InvalidLoginAttempts = 1},
				null,
				new UserDto(1, "test") {RoleName = "test", InvalidLoginAttempts = 1}
			}
			}).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new[] { a.SerialNumber, a.FatherSerialNumber, null } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new int[][] { new[] { a.Id }, new[] { 1 }, new[] { a.Id, 1 } } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new List<int> { a.Id, 1 } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new List<int>(5) { a.Id, 1 } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new List<int>(a.Id) { 1 } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new List<string>(a.Id) { a.SerialNumber, a.FatherSerialNumber, null } }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new
			{
				Enumerable = new List<UserDto>(a.Id)
				{
					new UserDto(a.Id, a.FatherSerialNumber) {RoleName = a.FatherSerialNumber},
					new UserDto(1, a.FatherSerialNumber) {RoleName = a.FatherSerialNumber, InvalidLoginAttempts = 1},
					null,
					new UserDto(1, "test") {RoleName = "test", InvalidLoginAttempts = 1}
				}
			}).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new[] { a.SerialNumber, a.FatherSerialNumber, null }[a.Id - a.Id].Length }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new { Enumerable = new List<string> { a.SerialNumber, a.FatherSerialNumber, null }[a.Id - a.Id].Length }).ToListAsync());
			Assert.DoesNotThrowAsync(() => db.Animals.Select(a => new
			{
				Enumerable = new Dictionary<string, string>
			{
				{ a.SerialNumber, a.FatherSerialNumber },
				{ "1", a.Father.SerialNumber },
				{ "2", null }
			}[a.SerialNumber]
			}).ToListAsync());
		}

		[Test]
		public async Task CanSelectConditionalSubClassPropertyValueAsync()
		{
			var animal = await (db.Animals.Select(
				               a => new
				               {
					               Pregnant = a is Mammal ? ((Mammal) a).Pregnant : false
				               })
			               .Where(o => o.Pregnant)
			               .ToListAsync());

			Assert.That(animal, Has.Count.EqualTo(1));
		}

		[Test]
		public async Task CanSelectConditionalEntityValueWithEntityComparisonRepeatAsync()
		{
			// Check again in the same ISessionFactory to ensure caching doesn't cause failures
			await (CanSelectConditionalEntityValueWithEntityComparisonAsync());
		}

		[Test]
		public async Task CanSelectConditionalObjectAsync()
		{
			var fatherIsKnown = await (db.Animals.Select(a => new { a.SerialNumber, Superior = a.Father.SerialNumber, FatherIsKnown = a.Father.SerialNumber == "5678" ? (object)true : (object)false }).ToListAsync());
			Assert.That(fatherIsKnown, Has.Exactly(1).With.Property("FatherIsKnown").True);
		}

		[Test]
		public async Task TestClientSideEvaluationAsync()
		{
			var list = await (db.Animals.Select(a => new
			{
				ClientSide = string.IsNullOrEmpty(a.FatherSerialNumber) ? 1 : 0,
				ClientSide2 = string.IsNullOrEmpty(a.Father.SerialNumber) ? 1 : 0
			}).ToListAsync());
			Assert.That(list.Select(o => o.ClientSide), Is.EquivalentTo(list.Select(o => o.ClientSide2)));

			var list2 = await (db.Animals.Select(a => new
			{
				ClientSide = a.Father.IsProxy(),
				ClientSide2 = a.FatherSerialNumber.IsProxy()
			}).ToListAsync());
			Assert.That(list2.Select(o => o.ClientSide), Is.EquivalentTo(list2.Select(o => o.ClientSide2)));

			var list3 = await (db.Orders.Where(o => o.OrderDate.HasValue).Select(o => new
			{
				ClientSide = o.OrderDate.Value.TimeOfDay.Days,
				ClientSide2 = o.OrderDate.Value
			}).ToListAsync());
			Assert.That(list3.Select(o => o.ClientSide), Is.EquivalentTo(list3.Select(o => o.ClientSide2.TimeOfDay.Days)));

			var list4 = await (db.Orders.Where(o => o.OrderDate.HasValue).Select(o => new
			{
				o.OrderId,
				ClientSide = o.OrderDate.Value.TimeOfDay.CompareTo(new TimeSpan(o.OrderId)),
				ClientSide2 = o.OrderDate.Value
			}).ToListAsync());
			Assert.That(list4.Select(o => o.ClientSide), Is.EquivalentTo(list4.Select(o => o.ClientSide2.TimeOfDay.CompareTo(new TimeSpan(o.OrderId)))));
		}

		[Test]
		public async Task TestServerAndClientSideEvaluationComparisonAsync()
		{
			var list = await (db.Animals.Select(
				a => new
				{
					ServerSide = (int?) a.Father.SerialNumber.Length,
					ClientSide = (int?) a.FatherSerialNumber.Length
				}).ToListAsync());
			Assert.That(list.Select(o => o.ServerSide), Is.EquivalentTo(list.Select(o => o.ServerSide)));

			var list1 = await (db.Animals
						 .Where(a => a.Father.SerialNumber != null)
						 .Select(
							 a => new
							 {
								 ServerSide = a.Father.SerialNumber.Length,
								 ClientSide = a.FatherSerialNumber.Length
							 })
						 .ToListAsync());
			Assert.That(list1.Select(o => o.ClientSide), Is.EquivalentTo(list1.Select(o => o.ServerSide)));

			var clientSide = await (db.Animals.Select(a => a.FatherSerialNumber.Length.ToString()).ToListAsync());
			var serverSide = await (db.Animals.Select(a => a.FatherSerialNumber.Length.ToString()).ToListAsync());
			Assert.That(clientSide, Is.EquivalentTo(serverSide));

			Assert.ThrowsAsync<GenericADOException>(
				() =>
				{
					return db.Animals.Select(
						a => new
						{
							ServerSide = a.Father.SerialNumber.Length
						}).ToListAsync();
				});

			Assert.ThrowsAsync<GenericADOException>(
				() =>
				{
					return db.Animals.Select(
						a => new
						{
							ClientSide = a.FatherSerialNumber.Length
						}).ToListAsync();
				});

			var list2 = await (db.Animals.Select(
				a => new
				{
					ServerSide = a.Father.SerialNumber.Length.ToString(),
					ClientSide = a.FatherSerialNumber.Length.ToString()
				}).ToListAsync());
			Assert.That(list2.Select(o => o.ClientSide), Is.EquivalentTo(list2.Select(o => o.ServerSide)));

			var list3 = await (db.Animals.Select(
				a => new
				{
					ServerSide = (int?) a.Father.SerialNumber.Substring(0, ((int?) a.Father.SerialNumber.Length - 1) ?? 0).Length,
					ClientSide = (int?) a.FatherSerialNumber.Substring(0, ((int?) a.FatherSerialNumber.Length - 1) ?? 0).Length
				}).ToListAsync());
			Assert.That(list3.Select(o => o.ClientSide), Is.EquivalentTo(list3.Select(o => o.ServerSide)));

			var list4 = await (db.Animals.Select(a => new
			{
				ServerSide = a.Father.SerialNumber,
				ClientSide = a.FatherSerialNumber,
				Test = (object) null
			}).ToListAsync());
			Assert.That(list4.Select(o => o.ClientSide), Is.EquivalentTo(list4.Select(o => o.ServerSide)));

			var list5 = await (db.Animals.Select(a => new
			{
				ServerSide = a.Father.SerialNumber == null,
				ClientSide = a.FatherSerialNumber == null
			}).ToListAsync());
			Assert.That(list5.Select(o => o.ClientSide), Is.EquivalentTo(list5.Select(o => o.ServerSide)));

			var list6 = await (db.Animals
						  .Where(a => a.Father.SerialNumber != null)
						  .Select(
							  a => new
							  {
								  ServerSide = -a.Father.SerialNumber.Length,
								  ClientSide = -a.FatherSerialNumber.Length
							  }).ToListAsync());
			Assert.That(list6.Select(o => o.ClientSide), Is.EquivalentTo(list6.Select(o => o.ServerSide)));

			var list7 = await (db.Animals
						  .Select(
							  a => new
							  {
								  ServerSide = a.Father != null ? a.Father.SerialNumber : null,
								  ClientSide = a.HasFather ? a.FatherSerialNumber : null
							  }).ToListAsync());
			Assert.That(list7.Select(o => o.ClientSide), Is.EquivalentTo(list7.Select(o => o.ServerSide)));

			var list8 = await (db.Animals
			              .Where(a => a is Dog)
			              .Select(
				              a => new
				              {
					              ServerSide = (long?) (int?) ((Dog) a).Father.SerialNumber.Length,
					              ClientSide = (long?) (int?) ((Dog) a).FatherSerialNumber.Length
				              }).ToListAsync());
			Assert.That(list8.Select(o => o.ClientSide), Is.EquivalentTo(list8.Select(o => o.ServerSide)));
		}

		public class Wrapper<T>
		{
			public T item;
			public string message;
		}

		private static void AssertOneSelectColumn(IQueryable query)
		{
			using (var sqlLog = new SqlLogSpy())
			{
				// Execute query
				foreach (var item in query) { }
				Assert.That(FindAllOccurrences(sqlLog.GetWholeLog(), "as col"), Is.EqualTo(1));
			}
		}

		private static int FindAllOccurrences(string source, string substring)
		{
			if (source == null)
			{
				return 0;
			}
			int n = 0, count = 0;
			while ((n = source.IndexOf(substring, n, StringComparison.InvariantCulture)) != -1)
			{
				n += substring.Length;
				++count;
			}
			return count;
		}
	}
}
